### ISSUE TITLE
ebsco CSS goobers up toolbar in admin UI

### ISSUE THREAD

**Issue by stopfstedt** [ebsco/edsapi-drupal-plugin#4]
Drupal 7.34 with default admin theme "seven".

![selection_017](https://cloud.githubusercontent.com/assets/1410427/6478566/cbd04af4-c1ea-11e4-81f2-05b5c81acba2.png)

It's this rule:

```css
.icon {
background: url("../images/sprites_32.png") no-repeat top left;
height: 32px;
line-height: 32px;
display: inline-block;
padding: 0 0 0 36px !important;
}
```

See https://github.com/ebsco/edsapi-drupal-plugin/blob/master/ebsco/css/ebsco.css#L386
